config/routes.rb
Rails.application.routes.draw do
  resources :informs
  resources :users do
    collection do
      get :user_inform
    end
  end
  
  get    '/about',  to: 'static_pages#about'
  get    '/edit',   to: 'users#user_inform'
  get    '/signup',  to: 'users#new'
  get    '/losts',    to: 'informs#lost'
  get    '/founds',    to: 'informs#found'   
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  
  root 'informs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inform.rb
class Inform < ApplicationRecord
belongs_to :user, optional: true
validates :user_id,  presence: true
validates :item_name,  presence: true, length: { maximum: 40 }
validates :detail,  presence: true, length: { maximum: 300 }
validates :date,  presence: true, length: { minimum: 8 }
validates :location,  presence: true, length: { maximum: 250 }
validates :contact,  presence: true, length: { maximum: 100 }
validates :pic_url,  presence: true, length: { maximum: 100 },url: true


end

app/models/user.rb
class User < ApplicationRecord
has_many :informs
validates :username,  presence: true, length: { maximum: 40 } , uniqueness: { case_sensitive: false }
has_secure_password
validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
validates :contact,  presence: true, length: { maximum: 255 }
validates :tel_number,  presence: true, length: { is: 10 } , numericality: { only_integer: true }
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/informs_controller.rb
class InformsController < ApplicationController
  before_action :set_inform, only: [:show, :edit, :update, :destroy]
  before_action :check_for_cancel, :only => [:create]
  # GET /informs
  # GET /informs.json
  def index
    @informs = Inform.all
  end

  # GET /informs/1
  # GET /informs/1.json
  def show
  end

  def lost
    @informs = Inform.where(:inform_type => "lost")
  end
  
  def found
    @informs = Inform.where(:inform_type => "found")
  end

  # GET /informs/new
  def new
    @inform = Inform.new
  end

  # GET /informs/1/edit
  def edit
  end

  # POST /informs
  # POST /informs.json
  def create
    @inform = Inform.new(inform_params)

    respond_to do |format|
      if @inform.save
        format.html { redirect_to @inform, notice: 'Inform was successfully created.' }
        format.json { render :show, status: :created, location: @inform }
      else
        format.html { render :new }
        format.json { render json: @inform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /informs/1
  # PATCH/PUT /informs/1.json
  def update
    respond_to do |format|
      if @inform.update(inform_params)
        format.html { redirect_to @inform, notice: 'Inform was successfully updated.' }
        format.json { render :show, status: :ok, location: @inform }
      else
        format.html { render :edit }
        format.json { render json: @inform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /informs/1
  # DELETE /informs/1.json
  def destroy
    @inform.destroy
    respond_to do |format|
      format.html { redirect_to informs_url, notice: 'Inform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_for_cancel
      if params[:commit] == "Reset"
        redirect_to new_inform_path
      end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inform
      @inform = Inform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inform_params
      params.require(:inform).permit(:user_id, :item_name, :detail, :date, :location, :contact, :pic_url, :inform_type)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid username/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
  def inform
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :check_for_cancel, :only => [:create]

    def index
    end
    # define attr
    def new
        @user = User.new
    end
    
    def user_inform
        @informs = Inform.where(:user_id => current_user.id)
    end
    
    # create user
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:info] = "Create Success!!."
            redirect_to root_url
        else
            render 'new'
        end
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def check_for_cancel
        if params[:commit] == "Reset"
        redirect_to '/signup'
        end
    end
    
    private
    #check input
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :contact, :tel_number)
    end
    
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/informs_helper.rb
module InformsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/informs/_form.html.erb
<% provide(:title, "New Inform") %>
<div class="form-group">
  <%= form_with(model: inform, local: true) do |form| %>
    <% if inform.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(inform.errors.count, "error") %> prohibited this inform from being saved:</h2>
  
        <ul>
        <% inform.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= form.hidden_field :user_id, id: :inform_user_id,value: current_user.id %>
    <div class="row">
      <div class="col-lg-12">
        <!--1-->
        <div class="row row-form">
          <div class="col-lg-2 project-topic">
            <%= form.label :item_name %>
          </div>
          <div class="col-lg-4">
            <%= form.text_field :item_name, id: :inform_item_name, class: 'form-control', placeholder: "- Fill your item name -"%>
          </div>
          <div class="col-lg-2 project-topic">
            <%= form.label :date %>
          </div>
          <div class="col-lg-4">
            <%= form.text_field :date, id: :inform_date, class: 'form-control', placeholder: " Example: yyyymmdd " %>
          </div>
        </div>  
        <!--2-->
        <div class="row row-form">
          <div class="col-lg-2 project-topic">
            <%= form.label :location %>
          </div>
          <div class="col-lg-4 project-topic">
            <%= form.text_field :location, id: :inform_location, class: 'form-control', placeholder: "- Fill your lost/found location -" %>
          </div>
          <div class="col-lg-2 project-topic">
            <%= form.label :contact %>
          </div>
          <div class="col-lg-4">
            <%= form.text_field :contact, id: :inform_contact, class: 'form-control', placeholder: "- Fill your contact -", value: current_user.contact  %>
          </div>
        </div> 
        <!--3-->
        <div class="row row-form">
          <div class="col-lg-2 project-topic">
            <%= form.label :pic_url %>
          </div>
          <div class="col-lg-4">
            <%= form.text_field :pic_url, id: :inform_pic_url, class: 'form-control', placeholder: "- Fill url of your picture -" %>
          </div>
          <div class="col-lg-2 project-topic">
            <%= form.label :inform_type %>
          </div>
          <div class="col-lg-2">
            <%= form.select(:inform_type, options_for_select([ ['found', "found"], ['lost', "lost"]] ), {}, {:class => 'form-control' })  %>
          </div>
        </div> 
        <!--4-->
        <div class="row row-form">
          <div class="col-lg-2 project-topic">
            <%= form.label :detail %>
          </div>
          <div class="col-lg-10">
            <%= form.text_field :detail, id: :inform_detail, class: 'form-control', placeholder: "- Fill your item detail -" %>
          </div> 
        </div>
      </div>
    </div>
    <div class="row">
        <div class="col-md-6 text-right">
            <%= form.submit "Reset" ,class: 'button-link'%>
        </div>
        <div class="col-md-6 text-left">
            <%= form.submit "Create" , class: 'button-link' %>
        </div>        
    </div>
    
  <% end %>

</div>

app/views/informs/edit.html.erb
<div class="about-header about-header-image project-topic"></div>
<% provide(:title, "Edit Inform") %>
<div class="container">    
    <div class="box-text-big">
        <div class="row">
            <div class="col-md-12" style="text-align: center;">
                <h3 class="project-topic" style="margin-top: 5px;margin-bottom: 20px">- Editing Inform -</h3>
                    <%= render 'form', inform: @inform %>
            </div>
        </div>
    </div>
</div>

app/views/informs/found.html.erb
<% provide(:title, "Found Items") %>
<div class="about-header about-header-image project-topic"></div>
<div class="container">    
    <div class="box-text-big">
        <div class="row">
            <div class="col-md-12" style="text-align: center;">
                <h3 class="project-topic" style="margin-top: 5px;margin-bottom: 20px">- Found Item Informs -</h3>
                    <p class="project-topic" id="see-more-text">- You can click on item to see more -</p>
                      <div class="row">
                        <% @informs.each do |inform| %>
                        <div class="col-lg-6 col-md-12 col-xs-12 text-center">
                          <%= link_to inform do %>
                          <div class="wrapper animated fadeIn">
                            <div class="item-img">
                              <img src="<%= inform.pic_url%>" , height="200", width="200">
                            </div>
                            <div class="item-info">
                              <div class="item-text">
                                <h1 class="project-topic found-header"><%= inform.item_name %></h1>
                                <div class="line-found-header"></div>
                                
                                <div class="row">
                                  <div class="col-lg-12 col-md-12">
                                      <p>location : <%= inform.location %></p>
                                  </div>
                                  
                                </div>
                                
                                <div class="row">
                                  <div class="col-lg-12 col-md-12">
                                      <p>Date : <%= inform.date %></p>
                                  </div>
                                  
                                </div>
                                
                                <div class="row">
                                  <div class="col-lg-12 col-md-12">
                                      <p>Contact : <%= inform.contact %></p>
                                  
                                  </div>
                                  
                                </div>
                                
                              </div>
                            </div>
                          </div>
                          <% end %>
                        </div>
                        
                      <% end %>
                  </div>
            </div>
        </div>
    </div>
</div>
                    

app/views/informs/index.html.erb
<% provide(:title, "Home") %>
<div class="about-header about-header-image project-topic"></div>
<div class="container">    
    <div class="box-text-big">
        <div class="row">
            <div class="col-md-12" style="text-align: center;">
                <h3 class="project-topic" style="margin-top: 5px;margin-bottom: 20px">- All Informs -</h3>
                
                <!--Example color-->
                <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-2"></div>
                    <!--lost color-->
                    <div class="col-lg-1 col-md-1 col-sm-1 example-color" style="background-color: #fdcb6e;">
                    </div>
                    <!--lost text-->
                    <div class="col-lg-2 col-md-3 col-sm-3">
                        <p id="example-text">Lost item</p>
                    </div>
                    <div class="col-lg-2 col-sm-1 col-md-1"></div>
                    <!--found color-->
                    <div class="col-lg-1 col-md-1 col-sm-1 example-color" style="background-color: #92c8e9;">
                    </div>
                    <!--found text-->
                    <div class="col-lg-2 col-md-1 col-sm-3">
                        <p id="example-text">Found item</p>
                    </div>
                    <div class="col-lg-2 col-sm-1 col-md-1"></div>
                </div>
                
                <!--for use text-->
                
                <p class="project-topic" id="see-more-text">- You can click on item to see more -</p>
                     <div class="row">
                        <% @informs.each do |inform| %>
                        <div class="col-lg-6 col-md-12 col-sm-12 text-center">
                        <%= link_to inform do %>
                        <div class="wrapper animated fadeIn">
                          <div class="item-img">
                              <img src="<%= inform.pic_url%>" , height="200", width="200">
                          </div>
                          <div class="item-info">
                            <div class="item-text">
                                
                                <% if inform.inform_type == "lost" %> 
                                    <h1 class="project-topic lost-header"><%= inform.item_name %></h1>
                                    <div class="line-lost-header"></div>
                                <% else %>
                                    <h1 class="project-topic found-header"><%= inform.item_name %></h1>
                                    <div class="line-found-header"></div>
                                <% end %>
                               
                              <div class="row">
                                <div class="col-lg-12 col-sm-12 text-left">
                                    <p>location : <%= inform.location %></p>
                                </div>
                              </div>
                              <div class="row">
                                <div class="col-lg-12 col-sm-12 text-left">
                                    <p>Date : <%= inform.date %></p>
                                </div>
                              </div>
                              <div class="row">
                                <div class="col-lg-12 col-sm-12 text-left">
                                    <p>Contact : <%= inform.contact %></p>
                                </div>
                              </div> 
                            </div>
                          </div>
                        </div>
                        <% end %>
                      </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/informs/lost.html.erb
<% provide(:title, "Lost Items") %>
<div class="about-header about-header-image project-topic"></div>
<div class="container">    
    <div class="box-text-big">
        <div class="row">
            <div class="col-md-12" style="text-align: center;">
                <h3 class="project-topic" style="margin-top: 5px;margin-bottom: 20px">- Lost Item Informs -</h3>
                     <p class="project-topic" id="see-more-text">- You can click on item to see more -</p>
                     <div class="row">
                        <% @informs.each do |inform| %>
                        <div class="col-lg-6 col-md-12 col-xs-12 text-center">
                        <%= link_to inform do %>
                        <div class="wrapper animated fadeIn">
                          <div class="item-img">
                              <img src="<%= inform.pic_url%>" , height="200", width="200">
                          </div>
                          <div class="item-info">
                            <div class="item-text">
                              <h1 class="project-topic lost-header "><%= inform.item_name %></h1>
                              <div class="line-lost-header"></div>
                              <div class="row">
                                <div class="col-lg-12 col-md-12">
                                    <p>location : <%= inform.location %></p>
                                </div>
                              </div>
                              <div class="row">
                                <div class="col-lg-12 col-md-12">
                                    <p>Date : <%= inform.date %></p>
                                </div>
                              </div>
                              <div class="row">
                                <div class="col-lg-12 col-md-12">
                                    <p>Contact : <%= inform.contact %></p>
                                </div>
                              </div> 
                            </div>
                          </div>
                        </div>
                        <% end %>
                      </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/informs/new.html.erb
<div class="about-header about-header-image project-topic"></div>
<div class="container">    
    <div class="box-text-big">
        <div class="row">
            <div class="col-md-12" style="text-align: center;">
                <h3 class="project-topic" style="margin-top: 5px;margin-bottom: 20px">- New Inform -</h3>
                    <%= render 'form', inform: @inform %>
            </div>
        </div>
    </div>
</div>

app/views/informs/show.html.erb
<% provide(:title, @inform.item_name) %>
<div class="container">    
    <div class="box-text-big">
        <div class="row">
            <div class="col-md-12" style="text-align: center;">
                <h3 class="project-topic" style="margin-top: 5px;margin-bottom: 20px">- Item Information -</h3>
                <div class="row">
                  <div class="col-lg-12">
                  <p id="notice"><%= notice %></p>
                      <img class="img-wrapper" src="<%= @inform.pic_url%>" , height="350", style="padding: 10px">
                  
                    <!--1-->
                    <div class="row row-form">
                      <div class="col-lg-2 col-sm-3 project-topic label-box">
                        <p>Item Name : </p>
                      </div>
                      <div class="col-lg-4 col-sm-3 show-box dt-wrapper">
                        <p><%= @inform.item_name %><p>
                      </div>
                      <div class="col-lg-2 col-sm-3 project-topic label-box">
                        <p>Date : </p>
                      </div>
                      <div class="col-lg-4 col-sm-3 show-box dt-wrapper">
                        <p><%= @inform.date %></p>
                      </div>
                    </div>  
                    <!--2-->
                    <div class="row row-form">
                      <div class="col-lg-2 col-sm-3 label-box">  
                        <p>Location : </p>
                      </div>
                      <div class="col-lg-4 col-sm-3 show-box dt-wrapper">
                        <p><%= @inform.location %></p>
                      </div>
                      <div class="col-lg-2 col-sm-3  label-box">
                        <p>Contact : </p>
                      </div>
                      <div class="col-lg-4 col-sm-3 show-box dt-wrapper">
                        <p><%= @inform.contact %></p> 
                      </div>
                    </div>  
                    <!--3-->
                    <div class="row row-form">
                      <div class="col-lg-2 col-sm-3 label-box">
                        <p>Detail : </p>
                      </div>
                      <div class="col-lg-4 col-sm-3 show-box dt-wrapper">
                        <p><%= @inform.detail %></p>
                      </div>
                      <div class="col-lg-2 col-sm-3 label-box">
                        <p>Type : </p>
                      </div>
                      <div class="col-lg-2 col-sm-3 show-box dt-wrapper"> 
                        <p><%= @inform.inform_type %></p>
                      </div>
                    </div> 
      
                  </div>
              </div>
            </div>
        </div>
    </div>
</div>






    

app/views/layouts/_footer.erb
<div class="footer" id ="footer-navbar" style="margin-top: 30px">
        <p class="project-topic" style="margin:10px">CN340 : Lost & Found Project</p>
      </div>

app/views/layouts/_header.html.erb
<div id="navbar">
    <b><p class="title-name"><i class="fas fa-box-open"></i> Lost&Found</p></b>
    <% if logged_in? %>
        <%= link_to "Logout" , logout_path, :method => :delete %>
        <%= link_to "About" , about_path %>
        <%= link_to "Profile", current_user %>
        <%= link_to "Edit inform" , edit_path %>
        <%= link_to "Inform" , new_inform_path %>
    <% else %>
        <%= link_to "Login" , login_path %>
        <%= link_to "About" , about_path %>
    <% end %>
    <%= link_to "Found Items" , founds_path %>
    <%= link_to "Lost Items" , losts_path %> 
    <%= link_to "Home" , root_path %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><%= yield(:title) %> | LostAndFound</title>
     <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="testproject/app/assets/stylesheets/bootstrap-material-design.css" rel="stylesheet">
        <link href="testproject/app/assets/stylesheets/main.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Quantico" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>
  <body>
        <%= render "layouts/header" %>
        <%= yield %>
        <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
        <%= render "layouts/footer" %>
      <script>
        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function() {scrollFunction()};
        
        function scrollFunction() {
          if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
            document.getElementById("myBtn").style.display = "block";
          } else {
            document.getElementById("myBtn").style.display = "none";
          }
        }
        
        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
          document.body.scrollTop = 0;
          document.documentElement.scrollTop = 0;
        }
      </script>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="about-header about-header-image project-topic"></div>
<div class="container"> 
    <div class="row">
        <div class="col-md-12">
            <div class="box-text-big" style="padding-bottom: 0px">
                <h3 class="project-topic text-center" style="margin-top: 5px">- About -</h3>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="box-text-big" style="border-right: solid  #66615b 0.75px ">
                <h3 class="project-topic text-center" style="margin-top: 5px">Lost & Found</h3>
                <h5 class="text-center title-thai">รายชื่อสมาชิก</h5>
                <div class="text-center">
                    <p style="line-height: 2em;">
                            นาย จีระวัฒน์ หนักแน่น 5710450031<br>
                            นาย ธีระพล ไวยนิยี 5810613413<br>
                            นางสาว ศิริรัตน์ บุณยัษเฐียร 5910490035<br>
                            นาย ภูริณัฐ ธรรมราช 5910613347
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="box-text-big">
                <h3 class="project-topic text-center" style="margin-top: 5px">Document</h3>
                <div class="row " style="padding-top: 20px">
                    <div class="col-md-1"></div>
                    <div class="col-md-5"><p>
                        <a href="https://drive.google.com/file/d/1VLooRiRulXW0MOmTysG1FS6iJ3AfDUw6/view?usp=sharing"><font style="color:#009688"><i class="fas fa-file-download"></i> ไฟล์ข้อเสนอ</font></a><br><br>
                        <a href="https://drive.google.com/file/d/1pjOzTfpvp7dKZLYRqMK_6GSUnULH1knG/view?usp=sharing"><font style="color:#009688"><i class="fas fa-file-download"></i> Feature</font></a><br><br>
                        <a href="https://drive.google.com/file/d/1hjHIndbGaFgm-b_KXnI_CpE768Ia8OoX/view?usp=sharing"><font style="color:#009688"><i class="fas fa-file-download"></i> Storyboard</font></a></p>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-5"><p>
                        <a href="https://drive.google.com/file/d/1ME-yGoZ0cqnUxqGe1vyvYMXLv-JT1EIx/view?usp=sharing"><font style="color:#009688"><i class="fas fa-file-download"></i> Requirements</font></a><br><br>
                        <a href="https://drive.google.com/file/d/13EmmlDJLRjeC1S0Qshjd9HQmjJdwAAgB/view?usp=sharing"><font style="color:#009688"><i class="fas fa-file-download"></i> ER-Diagram</font></a></p>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    <div class="row">
        <div class=col-md-12>
            <div class="box-text-big head-topic text-center" style="margin-top: 40px">
                <h4 class="project-topic">- Link -</h4><hr>
                <button class="button-link" onclick="window.location.href='https://www.pivotaltracker.com/n/projects/2223207'">Privotal Tracker</button>
                <button class="button-link" onclick="window.location.href='https://bitbucket.org/5810613413/testproject/src/poo'">Bitbucket Repository</button>
                <button class="button-link" onclick="window.location.href='https://www.youtube.com/playlist?list=PLzpL1Z_aTGhnyfyl9JVa5z6g_YcMGBL4j'">Youtube</button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class=col-md-12>
            <div class="box-text-big head-topic text-center" style="margin-top: 40px">
                <h4 class="project-topic">- Poster -</h4><hr>
                <image src="/assets/poster.jpg", width="800">
            </div>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="about-header about-header-image project-topic"></div>
<% if logged_in? === false %>
<div class="container">    
    <div class="box-text-big">
        <div class="row">
            <div class="col-md-12" style="text-align: center;">
                <h3 class="project-topic" style="margin-top: 5px;margin-bottom: 20px">- Sign up -</h3>
                    <%= render 'form', user: @user %>
            </div>
        </div>
    </div>
</div>
<% else %>
    <div class="container">    
    <div class="box-text-big">
        <div class="row">
            <div class="col-md-12" style="text-align: center;">
                <h3 class="project-topic" style="margin-top: 20px;margin-bottom:40px">- Please logout for signup -</h3>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/users/user_inform.html.erb
<div class="about-header about-header-image project-topic"></div>
<div class="container">    
    <div class="box-text-big">
        <div class="row">
            <div class="col-md-12" style="text-align: center;">
                <h3 class="project-topic" style="margin-top: 5px;margin-bottom: 20px">- Informs -</h3>
                    <p id="notice"><%= notice %></p>
                      <table>
                        <thead>
                          <tr>
                            <th>Item name</th>
                            <th>Date</th>
                            <th>Location</th>
                            <th>Type</th>
                            <th colspan="3">Operation</th>
                          </tr>
                        </thead>
                        <tbody>
                          <% @informs.each do |inform| %>
                            <tr>
                              <td><%= inform.item_name %></td>
                              <td><%= inform.date %></td>
                              <td><%= inform.location %></td>
                              <td><%= inform.inform_type %></td>
                              <td><%= link_to 'Show', inform %></td>
                              <td><%= link_to 'Edit', edit_inform_path(inform) %></td>
                              <td><%= link_to 'Destroy', inform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>
                    <br>
                <%= link_to 'New Inform', new_inform_path ,class: "button-link" %>
            </div>
        </div>
    </div>
</div>